### ISSUE TITLE
Plugin doesn't function correctly in Eclipse 4.x

### ISSUE THREAD

**Issue by wshager** [eXist-db/eclipse-plugin#1]
In Eclipse 4.2 I can't use a lot of keyboard shortcuts, like Find, Copy, etc.

**Comment by dizzzz** [comment]
Please could you describe what us wrong?

## 

Dannes Wessels

**Comment by wshager** [comment]
The xml documents opened in Eclipse don't respond to Delete, Ctrl + (C, X, V, A, F, etc.), when another document is open. It seems the focus is not properly set, or the editor doesn't recognize the tab.

Also, you can't open binary files in Eclipse, as you just get a lot of garbled Chinese characters.

**Comment by dizzzz** [comment]
I hope the code is still maintained...

## 

Dannes Wessels
